# Copyright © 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

import typing


class CabFile:
    def __init__(self, file: typing.Any): ...
    def __enter__(self) -> CabFile: ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    def __repr__(self) -> str: ...
    def write(self, filename: str, arcname: typing.Optional[str] = None) -> None: ...
    def writestr(self, arcname: str, data: bytes) -> None: ...
    def close(self) -> None: ...
